### ISSUE TITLE
Manifest version

### ISSUE THREAD

**Issue by SteveRussell33** [ab9st8/minimal-friction#1]
Needs to be changed to ``2.0.0`` for Rack v2 https://github.com/ab9st8/minimal-friction/blob/e7bfdb4307c53c9636f02c2346bf83432df31b5d/plugin.json#L4

**Comment by ab9st8** [comment]
Fixed in 51eebd1f25def24d581c5f69e1c2a4d654f67048, thanks for pointing out!
